version: "3.9"

services:
  sgp_api:
    build: .
    container_name: sgp_disconnect_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      API_TOKEN: ${API_TOKEN}
      SGP_USER: ${SGP_USER}
      SGP_PASS: ${SGP_PASS}
    volumes:
      - sgp_cookies:/app

volumes:
  sgp_cookies:
