services:
  sgp_api:
    build: .
    container_name: sgp_disconnect_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      COOKIES_FILE: "/cookies/sgp_cookies.pkl"
    volumes:
      - sgp_cookies:/cookies

volumes:
  sgp_cookies:
